FROM ubuntu:20.04

# Install dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata \
    && apt-get install -y curl wget gnupg2 \
    && apt-get install -y python3 python3-pip \
    && apt-get install -y xvfb libxi6 libgconf-2-4

RUN apt-get update && \
    apt-get install -y libnss3 libfontconfig1 libx11-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxi-dev libxtst-dev libxss1 libxrandr2 libasound2 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libxkbfile1 libxslt1.1 libxt6 xauth  && \
    rm -rf /var/lib/apt/lists/*

# Install Python 3.9 and pip
# RUN apt-get install -y python3.9 python3.9-dev python3-pip

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Playwright
RUN python3 -m pip install playwright

# Install browsers
RUN python3 -m playwright install

# Run the command
# CMD ["/bin/bash"]

# Run the test script
CMD ["python3", "test.py"]