FROM ubuntu:20.04

ENV GOOGLE_USER=google_user

# Install dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata \
    && apt-get install -y curl wget gnupg2 \
    && apt-get install -y python3 python3-pip \
    && apt-get install -y xvfb libxi6 libgconf-2-4

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Playwright
RUN python3 -m pip install playwright

# Install browsers
RUN python3 -m playwright install
RUN python3 -m playwright install-deps 

# Run the command
# CMD ["/bin/bash"]

# Run the test script
CMD ["python3", "test.py"]